import {
	Apple,
	Book,
	BookOpen,
	Calendar,
	Carrot,
	CookingPot,
	Droplets,
	Fence,
	FileText,
	Hammer,
	HeartHandshake,
	House,
	Leaf,
	MapPin,
	Recycle,
	Shovel,
	Sprout,
	Sun,
	Trees,
	Users,
	Utensils,
	Video,
	Wrench,
} from '@lucide/astro'

export const projectIconMap = {
	book: Book,
	leaf: Leaf,
	sprout: Sprout,
	carrot: Carrot,
	apple: Apple,
	house: House,
	'map-pin': MapPin,
	utensils: Utensils,
	'cooking-pot': CookingPot,
	users: Users,
	'heart-handshake': HeartHandshake,
	'book-open': BookOpen,
	'file-text': FileText,
	calendar: Calendar,
	video: Video,
	shovel: Shovel,
	hammer: Hammer,
	wrench: Wrench,
	fence: Fence,
	droplets: Droplets,
	recycle: Recycle,
	sun: Sun,
	trees: Trees,
} as const

export type ProjectIcon = keyof typeof projectIconMap
